export type PracticeQuestion = {
  id: string;
  subject: string;
  paper: string;
  topic: string;
  marks: number;
  commandTerm: string;
  difficulty: "easy" | "medium" | "hard";
  prompt: string;
  practiceMode?: "topic-drill" | "paper-practice" | "timed-mode" | "weakness-repair";
  lessonId?: string;
  questionType?: "concept-check" | "short-answer" | "mini-analysis" | "evaluation";
  paperMode?: "paper-1" | "paper-2" | "paper-3-hl";
};

export const questionBank: PracticeQuestion[] = [
  {
    id: "econ-u1-social-science-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "Economics as a social science",
    marks: 10,
    commandTerm: "Explain",
    difficulty: "easy",
    practiceMode: "topic-drill",
    lessonId: "economics-as-social-science",
    questionType: "short-answer",
    paperMode: "paper-1",
    prompt:
      "Explain why economists use simplified models when studying real-world choices.",
  },
  {
    id: "econ-u1-social-science-02",
    subject: "economics",
    paper: "Paper 1",
    topic: "Economics as a social science",
    marks: 10,
    commandTerm: "Analyze",
    difficulty: "medium",
    practiceMode: "paper-practice",
    lessonId: "economics-as-social-science",
    questionType: "mini-analysis",
    paperMode: "paper-1",
    prompt:
      "Analyze why correlation alone may be a weak basis for an economic policy decision.",
  },
  {
    id: "econ-u1-micro-macro-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "Microeconomics vs macroeconomics",
    marks: 10,
    commandTerm: "Explain",
    difficulty: "easy",
    practiceMode: "topic-drill",
    lessonId: "micro-vs-macro",
    questionType: "concept-check",
    paperMode: "paper-1",
    prompt:
      "Explain the difference between a microeconomic issue and a macroeconomic issue, using one example of each.",
  },
  {
    id: "econ-u1-concepts-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "Nine central concepts",
    marks: 10,
    commandTerm: "Apply",
    difficulty: "medium",
    practiceMode: "topic-drill",
    lessonId: "nine-central-concepts",
    questionType: "short-answer",
    paperMode: "paper-1",
    prompt:
      "Apply the concepts of equity and efficiency to a government subsidy for public transport.",
  },
  {
    id: "econ-u1-factors-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "Factors of production",
    marks: 10,
    commandTerm: "Explain",
    difficulty: "easy",
    practiceMode: "topic-drill",
    lessonId: "factors-of-production",
    questionType: "concept-check",
    paperMode: "paper-1",
    prompt:
      "Explain how land, labour, capital, and enterprise are used by a firm producing a service.",
  },
  {
    id: "econ-u1-scarcity-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "Scarcity and opportunity cost",
    marks: 10,
    commandTerm: "Explain",
    difficulty: "easy",
    practiceMode: "topic-drill",
    lessonId: "scarcity-choice-opportunity-cost",
    questionType: "short-answer",
    paperMode: "paper-1",
    prompt:
      "Explain how scarcity creates opportunity cost for households and governments.",
  },
  {
    id: "econ-u1-scarcity-02",
    subject: "economics",
    paper: "Paper 1",
    topic: "Scarcity and opportunity cost",
    marks: 15,
    commandTerm: "Discuss",
    difficulty: "medium",
    practiceMode: "paper-practice",
    lessonId: "scarcity-choice-opportunity-cost",
    questionType: "evaluation",
    paperMode: "paper-1",
    prompt:
      "Discuss whether opportunity cost is more important for governments than for individual consumers.",
  },
  {
    id: "econ-u1-systems-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "Economic systems",
    marks: 10,
    commandTerm: "Compare",
    difficulty: "medium",
    practiceMode: "topic-drill",
    lessonId: "economic-systems",
    questionType: "short-answer",
    paperMode: "paper-1",
    prompt:
      "Compare how free market and planned economies answer the question of how to produce.",
  },
  {
    id: "econ-u1-systems-02",
    subject: "economics",
    paper: "Paper 1",
    topic: "Economic systems",
    marks: 15,
    commandTerm: "Evaluate",
    difficulty: "medium",
    practiceMode: "timed-mode",
    lessonId: "economic-systems",
    questionType: "evaluation",
    paperMode: "paper-1",
    prompt:
      "Evaluate whether mixed economies are better able to respond to scarcity than pure market economies.",
  },
  {
    id: "econ-u1-ppc-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "PPC and circular flow",
    marks: 10,
    commandTerm: "Explain",
    difficulty: "easy",
    practiceMode: "topic-drill",
    lessonId: "ppc-circular-flow",
    questionType: "short-answer",
    paperMode: "paper-1",
    prompt:
      "Explain what a point inside a production possibilities curve shows.",
  },
  {
    id: "econ-u1-ppc-02",
    subject: "economics",
    paper: "Paper 1",
    topic: "PPC and circular flow",
    marks: 15,
    commandTerm: "Analyze",
    difficulty: "medium",
    practiceMode: "paper-practice",
    lessonId: "ppc-circular-flow",
    questionType: "mini-analysis",
    paperMode: "paper-1",
    prompt:
      "Analyze how an increase in investment could affect both the PPC and the circular flow of income.",
  },
  {
    id: "econ-u1-thought-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "Positive and normative economics",
    marks: 10,
    commandTerm: "Distinguish",
    difficulty: "easy",
    practiceMode: "topic-drill",
    lessonId: "positive-normative-economic-thought",
    questionType: "concept-check",
    paperMode: "paper-1",
    prompt:
      "Distinguish between positive and normative economic statements using one example of each.",
  },
  {
    id: "econ-u1-thought-02",
    subject: "economics",
    paper: "Paper 1",
    topic: "Positive and normative economics",
    marks: 15,
    commandTerm: "Discuss",
    difficulty: "hard",
    practiceMode: "weakness-repair",
    lessonId: "positive-normative-economic-thought",
    questionType: "evaluation",
    paperMode: "paper-1",
    prompt:
      "Discuss why economists may disagree about whether government intervention improves economic outcomes.",
  },
  {
    id: "econ-p1-market-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "Market Intervention",
    marks: 15,
    commandTerm: "Evaluate",
    difficulty: "medium",
    prompt:
      "Evaluate the impact of a price ceiling on the affordability of rental housing.",
  },
  {
    id: "econ-p1-demand-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "Demand",
    marks: 10,
    commandTerm: "Explain",
    difficulty: "easy",
    prompt:
      "Explain two non-price determinants that could shift demand for electric vehicles.",
  },
  {
    id: "econ-p1-elasticity-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "Elasticities",
    marks: 15,
    commandTerm: "Evaluate",
    difficulty: "medium",
    prompt:
      "Evaluate the usefulness of price elasticity of demand for a government considering a tax on sugary drinks.",
  },
  {
    id: "econ-p1-market-failure-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "Market failure",
    marks: 15,
    commandTerm: "Discuss",
    difficulty: "medium",
    prompt:
      "Discuss whether indirect taxes are the best response to negative externalities from air pollution.",
  },
  {
    id: "econ-p1-ad-as-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "AD-AS",
    marks: 15,
    commandTerm: "Evaluate",
    difficulty: "medium",
    prompt:
      "Evaluate the use of expansionary fiscal policy to reduce unemployment during a recession.",
  },
  {
    id: "econ-p1-supply-side-01",
    subject: "economics",
    paper: "Paper 1",
    topic: "Supply-side policies",
    marks: 15,
    commandTerm: "Evaluate",
    difficulty: "hard",
    prompt:
      "Evaluate market-based supply-side policies as a way to increase long-run economic growth.",
  },
  {
    id: "econ-p2-trade-01",
    subject: "economics",
    paper: "Paper 2",
    topic: "International Trade",
    marks: 20,
    commandTerm: "Discuss",
    difficulty: "hard",
    prompt:
      "Discuss the benefits and drawbacks of trade protectionism for a developing economy.",
  },
  {
    id: "econ-p2-exchange-01",
    subject: "economics",
    paper: "Paper 2",
    topic: "Exchange rates",
    marks: 15,
    commandTerm: "Analyze",
    difficulty: "medium",
    prompt:
      "Using a real-world context of your choice, analyze how currency depreciation may affect exporters, consumers, and inflation.",
  },
  {
    id: "econ-p2-development-01",
    subject: "economics",
    paper: "Paper 2",
    topic: "Development",
    marks: 15,
    commandTerm: "Discuss",
    difficulty: "medium",
    prompt:
      "Discuss whether investment in education is sufficient to improve economic development in a low-income economy.",
  },
  {
    id: "econ-p3-policy-01",
    subject: "economics",
    paper: "Paper 3",
    topic: "HL Paper 3",
    marks: 10,
    commandTerm: "Calculate",
    difficulty: "medium",
    prompt:
      "Given a fall in unemployment from 7.5% to 5.8%, calculate the percentage-point change and explain one policy implication.",
  },
  {
    id: "econ-p3-policy-02",
    subject: "economics",
    paper: "Paper 3",
    topic: "Policy recommendation",
    marks: 10,
    commandTerm: "Recommend",
    difficulty: "hard",
    prompt:
      "Recommend one policy mix for an economy facing high inflation and slowing growth. Justify using data, stakeholders, and limitations.",
  },
  {
    id: "geo-p1-urban-01",
    subject: "geography",
    paper: "Paper 1",
    topic: "Urban Environments",
    marks: 10,
    commandTerm: "Explain",
    difficulty: "easy",
    prompt:
      "Explain how urban land values change from the CBD to the rural-urban fringe.",
  },
  {
    id: "geo-p2-climate-01",
    subject: "geography",
    paper: "Paper 2",
    topic: "Climate Change",
    marks: 15,
    commandTerm: "To what extent",
    difficulty: "medium",
    prompt:
      "To what extent can urban planning reduce the impacts of climate-related hazards?",
  },
  {
    id: "engb-p1-media-01",
    subject: "english-b",
    paper: "Paper 1",
    topic: "Media",
    marks: 15,
    commandTerm: "Compare",
    difficulty: "medium",
    prompt:
      "Compare how two different media texts persuade teenagers to adopt healthy habits.",
  },
  {
    id: "math-aa-p2-prob-01",
    subject: "math-aa",
    paper: "Paper 2",
    topic: "Probability",
    marks: 10,
    commandTerm: "Solve",
    difficulty: "medium",
    prompt:
      "Solve a probability problem involving conditional events and interpret the result.",
  },
  {
    id: "cs-p1-networks-01",
    subject: "computer-science",
    paper: "Paper 1",
    topic: "Networks",
    marks: 15,
    commandTerm: "Explain",
    difficulty: "easy",
    prompt:
      "Explain how packet switching improves the efficiency of data transmission.",
  },
  {
    id: "bio-p2-ecology-01",
    subject: "biology",
    paper: "Paper 2",
    topic: "Ecology",
    marks: 20,
    commandTerm: "Evaluate",
    difficulty: "hard",
    prompt:
      "Evaluate the effectiveness of protected areas in conserving biodiversity.",
  },
  {
    id: "chem-p1-kinetics-01",
    subject: "chemistry",
    paper: "Paper 1",
    topic: "Kinetics",
    marks: 10,
    commandTerm: "Explain",
    difficulty: "easy",
    prompt:
      "Explain how temperature affects the rate of a chemical reaction using collision theory.",
  },
  {
    id: "phys-p2-waves-01",
    subject: "physics",
    paper: "Paper 2",
    topic: "Waves",
    marks: 15,
    commandTerm: "Discuss",
    difficulty: "medium",
    prompt:
      "Discuss how wave phenomena support the evidence for the wave-particle duality of light.",
  },
];
